substitutions:
  device_name: "purelinepro"

external_components:
  - source:
      type: local
      path: components

esphome:
  name: ${device_name}
  friendly_name: Novy Dampkap
  project:
    name: bwynants.$device_name
    version: "1.2"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: INFO
  logs:
    PurelinePro: INFO
    UART: INFO
    esp32_ble_client: INFO
    esp32.preferences: INFO
    light: INFO
    time: INFO
    text_sensor: INFO
    binary_sensor: INFO
    sensor: INFO
    fan: INFO
    button: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption
  services:
    # Service to send a custom cmd
    - service: custom_cmd
      variables:
        cmd_str: string
      then:
        - lambda: 'id(novydampkap)->send_cmd(cmd_str, "custom");'

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret main-wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: ${device_name} Fallback Hotspot
#    ap_timeout: 15s

captive_portal:

# do not use together with a bluetooth_proxy
web_server:
  port: 80

esp32_ble_tracker:
  max_connections: 1
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: false

ble_client:
  - mac_address: !secret purelinepro_extractor
    id: purelinepro_ble_id

purelinepro:
  - id: novydampkap

switch:
  - platform: purelinepro
    purelinepro_id: novydampkap
    recirculate:
      name: Recirculate
    enabled:
      name: Enabled

light:
  - platform: purelinepro
    purelinepro_id: novydampkap
    name: "Extractor Light"
    id: extractor_light
    restore_mode: RESTORE_DEFAULT_OFF

button:
  - platform: purelinepro
    purelinepro_id: novydampkap
    power:
      name: "Power Toggle"
    delayed_off:
      name: "Delayed Off"
    reset_grease:
      name: "Reset Grease"
    set_default_light:
      name: "Set Default Light"
    set_default_speed:
      name: "Set Default Speed"
  - <<: !include common/button/restart_button.yaml

fan:
  - platform: purelinepro
    purelinepro_id: novydampkap
    name: "Extractor Fan"
    id: extractor_fan
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: ble_rssi
    mac_address: !secret purelinepro_extractor
    name: "BLE RSSI"
    disabled_by_default: true
    entity_category: diagnostic

  - platform: purelinepro
    purelinepro_id: novydampkap
    off_timer:
      name: Off Timer
    boost_timer:
      name: Boost Timer
    grease_timer:
      name: Grease Timer
    operating_hours_led:
      name: Led Hours
    operating_hours_fan:
      name: Fan Hours
  - <<: !include common/sensor/memory.yaml
  - <<: !include common/sensor/wifi_strength.yaml

binary_sensor:
  - platform: purelinepro
    purelinepro_id: novydampkap
    boost:
      disabled_by_default: true
      name: Boost
    stopping:
      disabled_by_default: true
      name: Stopping

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Brussels

text_sensor:
  - <<: !include common/text-sensor/ip-adress.yaml
  - <<: !include common/text-sensor/uptime.yaml
